# Generated by Django 3.2.7 on 2022-06-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Chattogram', max_length=250, verbose_name='City'),
        ),
    ]
